# -*- coding: utf-8 -*-
"""Cópia de Explorando IA Generativa em um Pipeline de ETL com Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_dTJsoyajlQ7uaTyVTrMDAVuobMdraI
"""

import pandas as pd

dados_usuarios = pd.read_csv("SDW2023 - Página1.csv")

for index, row in dados_usuarios.iterrows():
    nome = row['Nome']
    limite_cartao_str = row['Limite do Cartão']
    saldo_conta_str = row['Saldo']

    limite_cartao_str = limite_cartao_str.replace('R$', '').replace('.', '').replace(',', '').strip()
    saldo_conta_str = saldo_conta_str.replace('R$', '').replace('.', '').replace(',', '').strip()

    try:
        limite_cartao = int(limite_cartao_str)
        saldo_conta = int(saldo_conta_str)

        if saldo_conta > 2000 and limite_cartao > 10000:
            mensagem = f"Olá {nome}, com um saldo saudável em sua conta e um alto limite de cartão, você está pronto para investir no futuro financeiro!"
        elif saldo_conta > 1000 and limite_cartao > 5000:
            mensagem = f"Olá {nome}, com um saldo sólido em sua conta e um bom limite de cartão, você pode explorar oportunidades de investimento."
        else:
            mensagem = f"Olá {nome}, considere verificar nossas opções de investimento para otimizar sua situação financeira."


        print(mensagem)
        print("\n")

    except ValueError:
        print(f"Erro ao processar os dados para {nome}.")